alexbocForum/Forum/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'Forum'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^logout$', login_required(views.LogoutRedirectView.as_view()), name='logout'),
]

alexbocForum/User/urls.py
from django.conf.urls import url

from . import views

app_name = 'User'
urlpatterns = [
    url(r'^$', views.LoginView.as_view(), name='login'),
]

alexbocForum/alexbocForum/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
import django

from Forum import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^User/', include('User.urls')),
    url(r'^Forum/', include('Forum.urls')),
]

urlpatterns += url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),

alexbocForum/Forum/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

alexbocForum/User/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from alexbocForum import settings as mysettings
from django.conf import settings
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
import hashlib
import os

def upload_avatar(instance, filename):
    fn, ext = os.path.splitext(filename)
    fn = instance.username
    filename = fn + ext
    pre_file_dir = os.path.join(mysettings.MEDIA_ROOT, ('avatars/%s' % (filename))).replace('\\', '/')

    if os.path.exists(pre_file_dir):
        os.remove(pre_file_dir)
    return os.path.join('avatars', filename)


class CustomUserManager(BaseUserManager):

    def _create_user(self, username, password, **extra_fields):
        if not username:
            raise ValueError('The given username must be set.')
        username = self.model.normalize_username(username)
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, password, **extra_fields)

    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, password, **extra_fields)


@python_2_unicode_compatible
class UserProfile(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=63, unique=True)

    nickname = models.CharField(_('Nickname'), max_length=255, blank=True, default='')
    sign = models.CharField(_('Personal Signature'), max_length=255, blank=True, default='')
    avatar = models.ImageField(upload_to=upload_avatar, default='avatars/default-avatar.png')

    is_active=models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD='username'
    REQUIRED_FIELD=['']

    objects=CustomUserManager()

    def __str__(self):
        return self.username

    def get_full_name(self):
          return self.username

    def get_short_name(self):
          return self.username

alexbocForum/Forum/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout as auth_logout
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.views.generic.base import View

User = get_user_model()

class IndexView(View):

    def get(self, request, *args, **kwargs):
        user = request.user
        if user.is_authenticated:
            print('I am ' + user.username)
            return render(request, 'Forum/index.html')
        else:
            return HttpResponseRedirect(reverse('User:login'))


class LogoutRedirectView(RedirectView):
    pattern_name = 'User:login'

    def get_redirect_url(self, *args, **kwargs):
        auth_logout(self.request)
        print('I log out successfully!')
        return super(LogoutRedirectView, self).get_redirect_url(*args, **kwargs)

alexbocForum/User/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import View

class LoginView(View):

    def get(self, request, *args, **kwargs):
        return render(request, 'User/Login.html')

    def post(self, request, *args, **kwargs):
        username = request.POST['user_name']
        password = request.POST['password']
        user = authenticate(request, username = username, password = password)
        if user is not None:
            auth_login(request, user)
            return HttpResponseRedirect(reverse('Forum:index'))
        else:
            return render(request, 'User/login.html')

alexbocForum/Forum/templates/Forum/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
<link rel = "Shortcut Icon" href="{% static 'img/indexicon.jpg' %}">
<title>index</title>
{% endblock %}

{% block css_js_static %}
{% endblock %}

{% block content %}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="#">2013</a></li>
        <li class="active">十一月</li>
    </ol>
</div>
<div class="container">
    <div id="myCarousel" class="carousel slide">
    <!-- 轮播（Carousel）指标 -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <div class="media">
    <a class="media-left" href="#">
        <img class="media-object" src="{% static 'img/indexicon.jpg' %}"
             alt="媒体对象" style="height:60px">
    </a>
    <div class="media-body">
        <h4 class="media-heading">媒体标题</h4>
        这是一些示例文本。这是一些示例文本。
        这是一些示例文本。这是一些示例文本。
        这是一些示例文本。这是一些示例文本。
        这是一些示例文本。这是一些示例文本。
        这是一些示例文本。这是一些示例文本。
    </div>
</div>
<div class="media">
    <a class="media-left" href="#">
        <img class="media-object" src="{% static 'img/indexicon.jpg' %}"
             alt="媒体对象" style="height:60px">
    </a>
    <div class="media-body">
        <h4 class="media-heading">媒体标题</h4>
        这是一些示例文本。这是一些示例文本。
        这是一些示例文本。这是一些示例文本。
        这是一些示例文本。这是一些示例文本。
        这是一些示例文本。这是一些示例文本。
        这是一些示例文本。这是一些示例文本。
        <div class="media">
            <a class="media-left" href="#">
                <img class="media-object" src="{% static 'img/indexicon.jpg' %}"
                     alt="媒体对象" style="height:60px">
            </a>
            <div class="media-body">
                <h4 class="media-heading">媒体标题</h4>
                这是一些示例文本。这是一些示例文本。
                这是一些示例文本。这是一些示例文本。
                这是一些示例文本。这是一些示例文本。
                这是一些示例文本。这是一些示例文本。
                这是一些示例文本。这是一些示例文本。
            </div>
        </div>
    </div>
</div>

    </div>
</div>
{% endblock %}

alexbocForum/User/templates/User/login.html
{% extends 'base.html' %}

{% block title %}
    <title>sign in</title>
{% endblock %}

{% block css_js_static %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'User/css/style.css' %}">
{% endblock %}

{% block nav %}
{% endblock %}

{% block content %}
    <div class="container  text-center" id="login-container">
		<form class="form-horizontal row col-lg-offset-4 col-lg-4" role="form" action="." method="POST">
            {% csrf_token %}
			<h3 class="form-title text-center"> Sign In </h3>
		  	<div class="form-group has-feedback">
			    <!-- <label for="username" class="col-lg-3 control-label">用户名</label> -->
			    <div class="col-lg-offset-1 col-lg-10">
			    	<span class="glyphicon glyphicon-user form-control-feedback"></span>
			      	<input type="text" class="form-control" name="user_name" placeholder="username" autofocus>
			    </div>
			</div>
			<div class="form-group has-feedback">
			    <!-- <label for="password" class="col-sm-3 control-label">密码</label> -->
			    <div class="col-lg-offset-1 col-lg-10">
			    	<span class="glyphicon glyphicon-lock form-control-feedback"></span>
			      	<input type="password" class="form-control" name="password" placeholder="password">
			    </div>
			</div>
			<div class="form-group">
		    	<div class="text-center">
		      		<button type="submit" class="btn btn-default">Sign In</button>
		    	</div>
		  	</div>
		</form>
	</div>
{% endblock %}

alexbocForum/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block title %}
    <title>alexboc</title>
    {% endblock %}

    {% load staticfiles %}
    <script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- {# <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> #} -->
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- {# <script src="{% static 'js/bootstrap.min.js' %}"> </script> #} -->

    {% block css_js_static %}
    {% endblock %}
</head>
<body>
    {% block nav %}
    <div class="container">
        <nav class="nav navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header col-lg-1 pull-left">
                    <img class="img-responsive img-circle" src="{% static 'img/indexicon.jpg' %}"/>
                </div>
                <div>
                    <form class="navbar-form navbar-left" role="search" action="#">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"> </span></button>
                    </form>
                </div>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <li><a href="#"><span class="glyphicon glyphicon-user"></span> 注册</a></li>
                        <li>
                            <!-- 按钮触发模态框 -->
                            <a href="#" data-toggle="modal" data-target="#myModal">
                                <span class="glyphicon glyphicon-log-in"></span>登录
                            </a>
                            <!-- 模态框（Modal） -->
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h4 class="modal-title" id="myModalLabel">模态框（Modal）标题</h4>
                                        </div>
                                        <div class="modal-body">
                                            <form class="form-herizontal" action="." method="post">
                                                <div class="form-group has-feedback">
                                    			    <!-- <label for="username" class="col-lg-3 control-label">用户名</label> -->
                                    			    <div class="">
                                    			    	<span class="glyphicon glyphicon-user form-control-feedback"></span>
                                    			      	<input type="text" class="form-control" name="user_name" placeholder="username" autofocus>
                                    			    </div>
                                    			</div>
                                                <div class="form-group has-feedback">
                                    			    <!-- <label for="password" class="col-sm-3 control-label">密码</label> -->
                                    			    <div>
                                    			    	<span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                    			      	<input type="password" class="form-control" name="password" placeholder="password">
                                    			    </div>
                                    			</div>
                                            </form>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                            <button type="button" class="btn btn-primary">提交更改</button>
                                        </div>
                                    </div><!-- /.modal-content -->
                                </div><!-- /.modal -->
                            </div>
                        </li>

                        <li> <a href="{% url "Forum:logout" %}"> <span class="glyphicon glyphicon-log-out"></span>登出</a> </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    {% endblock %}

    {% block content %}

    {% endblock %}
</body>
</html>